/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
// @ts-check
import { google } from 'googleapis';
import { splitArrayIntoChunk } from './utils.js';

/**
 * @param {string} playlistId Playlist ID
 * @param {string} pageToken nextPageToken
 * @returns {Promise<import('googleapis').youtube_v3.Schema$PlaylistItemSnippet[]>}
 */
export const fetchPlaylist = async (playlistId, pageToken = undefined) => {
	const res = await google.youtube('v3').playlistItems.list({
		key: process.env.API_KEY,
		part: ['snippet'],
		maxResults: 50,
		playlistId,
		pageToken
	});

	return res.data.items?.map((item) => item.snippet)?.filter((item) => item != null) ?? [];
};

/**
 * @param {string[]} videoIds Video ID
 * @returns {Promise<import('googleapis').youtube_v3.Schema$Video[]>}
 */
export const fetchVideos = async (videoIds) => {
	const maxResults = 50;
	const results = await Promise.all(
		splitArrayIntoChunk(videoIds, maxResults).map(async (ids) => {
			const res = await google.youtube('v3').videos.list({
				key: process.env.API_KEY,
				part: ['snippet', 'status'],
				maxResults,
				id: ids
			});
			return res.data.items ?? [];
		})
	);

	return results.flat();
};

/**
 * @param {string} description
 * @returns {boolean}
 */
export const isAutoGeneratedVideo = (description) =>
	description.match(/^Provided to YouTube.+Auto-generated by YouTube\.$/s) != null;
